### ISSUE TITLE
windows can crash in big directory structures

### ISSUE THREAD

**Issue by Byron** [Byron/godi#16]
Might be related to windows paths.
Thanks to @mottosso

``` bash
SEAL COMPLETE: ->READ #3 #Δ3/s ⌰229.93MiB Δ271.48MiB/s | HASH ⌰459.86MiB Δ542.96MiB/s

byron@STEELBOOK>..\godi.exe verify godi_2014-07-25_214648.gobz
panic: runtime error: slice bounds out of range

goroutine 26 [running]:
runtime.panic(0x5dae00, 0x748f6f)
/usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/panic.c:279 +0x11f
github.com/Byron/godi/api.Gather(0xc08200c660, 0xc0820202a0, 0xc082006fa0, 0xc08200c328, 0x676f88, 0
xc0820486c0, 0x0, 0x0, 0x0)
.../dev/go-lib/src/github.com/Byron/godi/api/gather.go:122 +0x13f3
github.com/Byron/godi/verify.(*VerifyCommand).Gather(0xc08200c300, 0xc08200c660, 0xc0820202a0, 0xc08
2006fa0)
.../dev/go-lib/src/github.com/Byron/godi/verify/types.go:103 +0x7a
created by github.com/Byron/godi/api.StartEngine
.../dev/go-lib/src/github.com/Byron/godi/api/types.go:233 +0x398

goroutine 16 [semacquire]:
sync.runtime_Semacquire(0xc082000930)
/usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/sema.goc:199 +0x37
sync.(*WaitGroup).Wait(0xc082007060)
/usr/local/Cellar/go/1.3/libexec/src/pkg/sync/waitgroup.go:129 +0x152
github.com/Byron/godi/api.StartEngine(0x3147c0, 0xc08200c300, 0xc082006f20, 0xc082006f20, 0x0, 0x0)
.../dev/go-lib/src/github.com/Byron/godi/api/types.go:269 +0x5cb
github.com/Byron/godi/cli.RunAction(0x3147c0, 0xc08200c300, 0xc0820420b0)
.../dev/go-lib/src/github.com/Byron/godi/cli/cli.go:87 +0xfa
github.com/Byron/godi/verify.func┬À001(0xc0820420b0)
.../dev/go-lib/src/github.com/Byron/godi/verify/cli.go:25 +0x60
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc08201c180, 0xc0820420b0, 0x0, 0x0)
.../dev/ext/go-lib/src/github.com/codegangsta/cli/app.go:217 +0x966
github.com/codegangsta/cli.Command.startApp(0x60aed0, 0x6, 0x600710, 0x0, 0x648970, 0x32, 0x0, 0x0,
0x0, 0xc082000340, ...)
.../dev/ext/go-lib/src/github.com/codegangsta/cli/command.go:140 +0x20b
github.com/codegangsta/cli.Command.Run(0x60aed0, 0x6, 0x600710, 0x0, 0x648970, 0x32, 0x0, 0x0, 0x0,
0xc082000340, ...)
.../dev/ext/go-lib/src/github.com/codegangsta/cli/command.go:40 +0xe2d
github.com/codegangsta/cli.(*App).Run(0xc08201c0c0, 0xc082005da0, 0x3, 0x3, 0x0, 0x0)
.../dev/ext/go-lib/src/github.com/codegangsta/cli/app.go:127 +0x948
main.main()
.../dev/go-lib/src/github.com/Byron/godi/godi.go:14 +0x73

goroutine 19 [finalizer wait]:
runtime.park(0x414d50, 0x74c8f8, 0x74aaa9)
/usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/proc.c:1369 +0xac
runtime.parkunlock(0x74c8f8, 0x74aaa9)
/usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/proc.c:1385 +0x42
runfinq()
/usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/mgc0.c:2644 +0xdd
runtime.goexit()
/usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
/usr/local/Cellar/go/1.3/libexec/src/pkg/os/signal/signal_unix.go:21 +0x25
created by os/signal.init┬À1
/usr/local/Cellar/go/1.3/libexec/src/pkg/os/signal/signal_unix.go:27 +0x39

goroutine 21 [chan receive]:
github.com/Byron/godi/utility.func┬À002()
.../dev/go-lib/src/github.com/Byron/godi/utility/reader.go:193 +0x68
created by github.com/Byron/godi/utility.NewReadChannelController
.../dev/go-lib/src/github.com/Byron/godi/utility/reader.go:199 +0x1a1

goroutine 23 [chan receive]:
github.com/Byron/godi/cli.func┬À001()
.../dev/go-lib/src/github.com/Byron/godi/cli/cli.go:36 +0xa8
created by github.com/Byron/godi/cli.MakeStatisticalLogHandler
.../dev/go-lib/src/github.com/Byron/godi/cli/cli.go:52 +0x165

goroutine 24 [chan receive]:
github.com/Byron/godi/api.func┬À004()
.../dev/go-lib/src/github.com/Byron/godi/api/types.go:224 +0x4b
created by github.com/Byron/godi/api.StartEngine
.../dev/go-lib/src/github.com/Byron/godi/api/types.go:226 +0x292

goroutine 25 [chan send]:
github.com/Byron/godi/verify.func┬À003(0xc08200c660, 0xc08200c6c0)
.../dev/go-lib/src/github.com/Byron/godi/verify/types.go:74 +0x50e
github.com/Byron/godi/api.func┬À001()
.../dev/go-lib/src/github.com/Byron/godi/api/algo.go:17 +0x9c
created by github.com/Byron/godi/api.Generate
.../dev/go-lib/src/github.com/Byron/godi/api/algo.go:18 +0xf2

goroutine 27 [runnable]:
sync.runtime_Semacquire(0xc082084010)
/usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/sema.goc:199 +0x37
sync.(*WaitGroup).Wait(0xc082006fa0)
/usr/local/Cellar/go/1.3/libexec/src/pkg/sync/waitgroup.go:129 +0x152
github.com/Byron/godi/api.func┬À005()
.../dev/go-lib/src/github.com/Byron/godi/api/types.go:236 +0x36
created by github.com/Byron/godi/api.StartEngine
.../dev/go-lib/src/github.com/Byron/godi/api/types.go:238 +0x3ea

goroutine 28 [chan receive]:
github.com/Byron/godi/api.func┬À002()
.../dev/go-lib/src/github.com/Byron/godi/api/algo.go:64 +0x137
created by github.com/Byron/godi/api.Aggregate
.../dev/go-lib/src/github.com/Byron/godi/api/algo.go:84 +0x126

goroutine 29 [chan receive]:
github.com/Byron/godi/api.func┬À008()
.../dev/go-lib/src/github.com/Byron/godi/api/types.go:256 +0x71
created by github.com/Byron/godi/api.StartEngine
.../dev/go-lib/src/github.com/Byron/godi/api/types.go:260 +0x55f

goroutine 30 [chan receive]:
github.com/Byron/godi/api.func┬À009()
.../dev/go-lib/src/github.com/Byron/godi/api/types.go:263 +0x71
created by github.com/Byron/godi/api.StartEngine
.../dev/go-lib/src/github.com/Byron/godi/api/types.go:267 +0x5bb
Marcus • 1 min
```

**Comment by Byron** [comment]
@mottosso
There have been quite some improvements in the meanwhile, and I have done some windows testing too. If you find the time, you can try [godi 0.5](https://dl.dropboxusercontent.com/u/17820808/godi.exe)  and retry the seal operation to verify it's fixed.
[Problems with the character display in the terminal](#20) will be handled tomorrow - apparently the OSX shell is pretty special as it shows characters no other tested shell can.

**Comment by Byron** [comment]
Actually I managed to reproduce the issue - it was related using relative paths to seal files.
The issue was fixed.
